spring.mongodb.uri=${SPRING_MONGODB_URI}
# Keep this for UUID support
spring.data.mongodb.uuid-representation=standard

spring.main.allow-circular-references=true
spring.data.mongodb.auto-index-creation=true
spring.profiles.active=dev
server.port=${PORT:8080}

application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY}

paystack.secret.key=${PAYSTACK_SECRET_KEY}
paystack.base.url=${PAYSTACK_BASE_URL}

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

# MUST use these for port 465
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

# Increase timeouts to give the handshake more time
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

